# originally designed for
# - Docker version:         18.09.1
# - docker-compose version:  1.21.0

# latest supported composefile version at time of writing
# (could probably work for earlier versions, but not tested)
version: '3.6'

services:
  web:
    build: .
    ports:
    - '80:8000/tcp'
    depends_on:
    - db
    networks:
    - wan
    - lan
  db:
    image: postgres:alpine
    volumes:
    - dbdata:/var/lib/postgresql/data
    networks:
    - lan

volumes:
  dbdata:

networks:
  wan:
  lan:
    internal: true
