# Generated by Django 2.2.4 on 2020-03-04 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('project', '0002_projectattributetype_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojectattributetype',
            name='custom_boolean_choice',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='utils.CustomizedBooleanChoice'),
        ),
        migrations.AddField(
            model_name='projectattributetype',
            name='custom_boolean_choice',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.CustomizedBooleanChoice'),
        ),
    ]
